INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 1, 20, '생원유로 만든 진짜 카이막' , '현재 그대로 진짜 카이막', '후처리 압축과정을 통한 더 진하고 깊은 맛', '#카이막', 500000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 20, '젤라또처럼 진하고 꾸덕한 그릭요거트' , '젤라또인가 그릭요거트인가', '신맛은 줄이고, 단맛은 더욱 극대화 했습니다.', '#그릭요거트', 600000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 20, '170시간 절구에 갈아 만든 썰어 먹는 초콜릿' , '170시간 절구갈아 만든 초콜릿', 'Bean to Bar 과정을 통해 만든', '#초콜릿', 700000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 4, 20, '화이트데이 쿠키 박스' , '화이트데이 쿠키 박스', '버터와 초콜렛으로 펼칠 수 있는 사랑스러운 쿠키박스', '#쿠키', 800000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 20, '맛과 영양 가득 천연벌꿀' , '천연벌꿀, 감귤꽃꿀', '각종 비타민과 천연 당분이 풍부합니다.', '#천연벌꿀', 900000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 40, '푹신푹신 햄스터 키링' , '푹햄이들 인형키링', '푹햄이 만지면서 힐링하세요', '#인형 키링', 800000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 1, 40, '말랑쫀득 펭귄인형' , '말랑쫀득 펭귄인형', '일상에서 함께 하는 말랑쫀득 펭귄인형', '#캐릭터 인형', 700000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 50, '눈으로 볼 수 없는 살냄새' , '매력의 향기 코튼 스노우', '깔끔하고, 군더더기 없는 깨끗한 향기', '#코튼향', 600000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 50, '일상 속에서 보내는 매일의 일과에 맡는 한 냄새' , '궁금한 냄새, 너', '파우더리한 따듯하고 부드러운 느낌의 향', '#파우더리향', 400000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 4, 50, '로맨스 판타지 세계의 향' , '향수를 뿌리고 일어나니 내가 황녀?', '잊혀진 비밀스러운 기억이 떠오르는 향기', '#플라워향', 300000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 50, '아이스크림 이제 먹지말고 뿌리자' , '화제의 아이스크림 향수', '맛뿐 아니라 향으로도 즐기는 바닐라 향수', '#바닐라향', 500000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 50, '달콤하게 퍼지는 고당도 포도향 향수' , '달콤한 한도초과! 향기로 즐겨요', '샤인머스켓을 그래도 농축시킨것 같은 달콤한 향기', '#프루티향', 600000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 1, 50, '새하얀 백도를 갈아넣은듯한 향기' , '한입 베어물때 그 향기, 백도 아삭', '인위적이지 않은 자연스럽게 달콤한 냄새', '#프루티향', 300000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 70, '털빠짐 없는 고양이 키우기' , '랜선집사가 되어보자 <야옹홈>', '현실에서 고양이를 못 키우는분들을 위한', '#고양이육성', 600000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 70, '마법 레시피를 찾아 강아지 친구와 요리하는 게임' , '강아지가 요리 해준다? <강아지와 비밀레시피>', '할아버지의 편지를 받고 도착한 이곳은?', '#요리게임', 500000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 4, 70, 'AI애인의 호감도를 올려 공략해보자' , '당신을 설레게 할 AI 애인', '호감도를 올려 목표를 달성해보자!', '#AI', 800000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 70, '어디서든 즐기는 엑셀 방탈출게임' , '첫번째 에피소드 <악몽>', '사무용으로 쓰이는 엑셀 프로그램을 이용한 방탈출게임', '#엑셀방탈출', 300000, '2024-02-19', '2024-03-18', '2024-03-25', '2024-04-01', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 70, '카톡만 있으면 할 수 있는 방탈출게임' , '카톡 두근두근 로맨스', '카톡 챗봇 기술을 활용한 연애 시뮬레이션 게임', '#카톡게임', 500000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 1, 80, '모든 연령대의 사람들이 함께 입을 수 있는 추리닝' , '남녀노소를 위한 배색 집업 추리닝', '다가올 봄을 위한 편하고 예쁜 추리닝', '#추리닝', 400000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 80, '고수 조아 클럽의 티셔츠' , '고수조아클럽 티셔츠와 함께하는 맛있는 여행', '고수를 좋아하는 그대, 여행지에서 이 옷을 보여주세요', '#고수좋아', 700000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 80, '구멍나는 팬티는 이제 그만 질긴팬티' , '도깨비빤스', '찢어질 걱정 없는 팬티', '#도깨비', 700000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 4, 80, '속옷같지 않은 트렁크 팬티' , '속옷같지 않은 속옷, 트렁크 팬티', '자취방에서 하의는 편히 트렁크 팬티만 입어도 되게', '#언더웨어', 400000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 1, 80, '전세계 생산량 5% 명품울로 만든 캐시미어 코트' , '캐시미어 맥코트', '올 겨울에도 이 코트 하나면 끝', '#캐시미어', 900000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 80, '겨울 싫은 사람들 모여라 윈터 헤이트 클럽' , '윈헤클 티셔츠', '누구나 마음 한켠에 겨울을 싫어하는 마음을 안고 살죠', '#겨울싫어', 300000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 90, '소작인으로 시작해 대지주까지' , '사표내고 이계에서 농사짓습니다 1~2권', '소작인으로 시작해 대지주까지 즐기는 힐링 라이프', '#농사', 500000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 4, 90, 'N사 인기 웹툰 <여주의 첫날밤을 가져버렸다> 단행본' , 'N사웹툰<여주의 첫날밤을 가져버렸다> 단행본 4~6권', '본편 완결까지 담은 단행본 4~6권', '#로맨스판타지', 800000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 90, '서유럽 신화를 만화로 배워보자' , '판타지 근본, 본격 서유럽 신화 만화 1권', '드디어 제대로 된 근본 서유럽 신화 만화 등장', '#신화', 300000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 90, '20세기를 살아가는 x세대의 고군분투 생존기' , '람자 이야기', '람자의 고군분투 생존기를 그린 에세이', '#에세이', 100000, '2024-02-20', '2024-03-19', '2024-03-26', '2024-04-02', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 1, 90, '인스타툰 모음 <엔프피 설명서>' , '속을 알기 쉬운 <엔프피 설명서>', '속을 알기 쉬운 ENFP 진짜를 말하다', '#MBTI', 400000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 90, '첫째 쭈구리가 기록하는 일상/가족툰' , '첫째들 모여! 세 자매의 첫째 <쭈굴쭈굴 가족일기>', '이런분께 추천드려요! 첫째이신 분', '#일상툰', 200000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 90, '여섯 마법소년들이 펼치는 짜릿한 액션활극' , '<마법소년 저세계아이돌> 단행본 & 공식 굿즈', '<마세돌> 단행본 & 특별 화보집 및 굿즈', '#마세돌', 900000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 4, 100, '편리하고, 안전하게 전동 눈썹 정리기' , '위잉위잉 프리미엄 전동 눈썹 정리기', '칼날, 색상, 배터리 업그레이드', '#눈썹정리', 300000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 100, '따뜻함과 귀여움을 동시에' , '치즈 고양이 인형 보조배터리', '귀엽고 실용성도 높은 제품', '#보조배터리', 300000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 100, '트렌디한 기능으로 꽉찬 똑똑한 가습기' , '물멍 할 수 있는 무중력 가습기', '건강을 위해 깨끗한 방식의 가습기를 만들었습니다.', '#가습기', 600000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 1, 100, 'UV-C로 강력한 살균' , '늘 새것처럼 깨끗하게 칫솔 살균기', '건조, 살균 전부 가능한 칫솔 살균기', '#칫솔살균기', 300000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 2, 100, '티 나지 않는 사원증 녹음기' , '직장인 필수템 사원증 녹음기', '근무중 위협으로 인한 최소한의 방어수단', '#녹음기', 600000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 3, 100, '언제나 깨끗한 고양이 화장실' , '모두를 위한 고양이 자동 화장실', '용변을 본 후 10분 뒤 자동으로 청소', '#자동 화장실', 900000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 4, 110, '손목 아픈 사람들을 위한 테이핑 손목보호대' , '손목 조진놈이 만든 테이핑 보호대', '건초염으로 고생하는 분들은 우한 손목 보호대', '#손목 보호대', 500000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 4, 110, '실력 상관 없이 수영에 미친 분들을 위한 수모' , '수영장 패셔니스타 가능한 수모', '밀착력 좋고 귀여운 수친놈 수모', '#압축파우치', 500000, '2024-02-21', '2024-03-20', '2024-03-27', '2024-04-03', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 5, 120, '항상 변하는 여러가지 모양의 구름' , '시시각각 변하는 구름의 모양', '찰나의 순간들을 엮은 사진 엽서북', '#구름사진', 800000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 6, 120, '치앙마이 풍경을 담은 엽서북과 스티커' , '꽃, 치앙마이 엽서북', '10가지 꽃과 여행을 주제로 묶은 20종의 엽서북', '#꽃', 400000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 7, 120, '치즈색 고양이 엽서책' , '하나, 둘, 셋, 치즈', '라미와 동락이의 일상을 담은 엽서책', '#고양이 엽서', 600000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 8, 120, '감성사진 색감 필터' , '쇼핑몰 사원이 만든 사진필터', '비싼 유료필터, 라이트룸 강좌 필요 없는 사진 필터', '#사진필터', 200000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 9, 120, '10년간 여행 다니며 담은 나무 사진들' , '나무 같은 사람, 나무여행 사진집', '여행 다닐때 느낌 그대로 사진에 담았습니다', '#나무', 400000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 10, 120, '제주도 바다 패브릭 포스터' , '제주도를 추억하는 방식 패브릭 포스터', '육지에서는 느끼지 못한 감성들을 담아봤습니다.', '#제주바다', 300000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 11, 120, '북미,남미,유럽 등 여행하며 찍은 지평선이 담긴 엽서북' , '여행 중 만난 지평선 연결 엽서북', '사진밖으로 연결되는 세계 각지의 순간을 함께', '#지평선' 800000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 12, 120, '야생화 엽서북' , '야생화 엽서북', '엽서에 이름, 학명, 문장을 적어서 어디 풍경인지 알 수 있어요', '#꽃', 300000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 13, 120, '엽서보다 더 물 같은 문진' , '물의 순간, 아카이브 오브 워터', '종이를 누르는 용도 또는 공간을 꾸미는 오브제로 활용 가능', '#문진', 700000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 14, 120, '25 똥괭이네 굿즈' , '25 똥괭이네 포스터북 2종', '아이들의 귀염뽀짝한 사진으로 엽서북을 제작', '#똥괭이네', 500000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 15, 120, '펀딩을 100% 달성할때마다 필름자판기의 설치 장소 추가' , '언제 어디서든 필요할때마다 전국 필름 자판기 설치', '디지털 세대가 필름에 관심을 갖게 해주는 역할', '#필름 자판기', 900000, '2024-02-22', '2024-03-21', '2024-03-28', '2024-04-04', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 16, 120, '세 작가의 작은 전시회' , '세 작가의 작은 전시회, 엽서북 사진전', '당신의 공간에서 작은 전시회를 열어보세요', '#엽서북', 200000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 17, 130, '우리 아이를 위한 말랑하고 맛있는 츄르스틱' , '수의사의 바른 먹거리 츄잉스틱', '필수영양소가 들어간 건강하고 맛있는 츄잉스틱', '#개껌', 600000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 18, 130, '천연깃털만 사용한 핸드메이드 고양이 장난감' , '천연깃털만 사용한 고양이 장난감', '물빠짐 없는 안전한 핸드메이드 깃털 장난감', '#고양이 장난감', 300000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 19, 130, '고양이 구내염 개선촉진 스프레이' , '모든 고양이를 위한 캣따비 스프레이', '세상 모든 고양이 구내염 개선 촉진 프로젝트', '#고양이 영양제', 500000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 20, 130, '반려동물도 같이 마실 수 있는 와인' , '강아지 고양이 와인 츄와인', '제주지역의 무항생제 치킨으로 제조', '#반려동물 간식', 400000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 21, 130, '놀이와 치석제거를 한번에' , '놀이부터 치석제거까지 1석2조 장난감', '천연고무로 만든 강아지 노즈워크 장난감', '#강아지 장난감', 800000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 22, 130, '세상에 단 하나뿐인 고양이 츄르짜개' , '마지막까지 츄릅 고양이 전용 츄르짜개', '이름을 각인할 수 있고, 키링으로 쓸 수 있어요', '#고양이 츄르짜개', 400000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 23, 130, '고양이 전용 밀크티' , '고양이와 티타임', '고양이가 좋아하는 허브4종', '#개껌', 500000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 24, 140, '신비로운 행성으로 가기 위한 문을 열 수 있는 열쇠' , '꿈꾸던 세계로, 저세계 열쇠 목걸이', '신비롭고 오묘한 빛의 천연석으로 셋팅', '#목걸이', 600000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 25, 140, '영원한 우리 우정의 서약서' , '우정의 서약, 우정 목걸이', '1/n씩 나눠가질 수 있어요', '#목걸이', 600000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 26, 140, '향기를 넣어 보관하세요' , '어디에도 없는 향기 목걸이', '향수를 스톤이 먹금게 해주면 일주일 이상 향이 지속되요', '#목걸이', 600000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 27, 140, '다이아몬드를 대체할 모이사나이트' , '다이아몬드를 대체할 모이사나이트', '다이아몬드와 비슷하지만 더 친환경적인', '#모이사나이트', 400000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');

INSERT INTO TB_PROJECT(PROJECT_NO, PROJECT_SELLER, PROJECT_CATEGORY_NO, PROJECT_OVERVIEW, PROJECT_TITLE, PROJECT_CONTENT, PROJECT_TAG, PROJECT_PRICE, PROJECT_START, PROJECT_END, PROJECT_PAYMENT_BUYER, PROJECT_PAYMENT_SELLER, PROJECT_STATUS) 
VALUES(SEQ_PROJECT_NO.NEXTVAL, 24, 140, '살고싶은 삶을 성취할 수 있도록 지지하고 도와주는 원석' , '악몽을 걸러주는 드림캐쳐 목걸이', '착용할수록 내 몸에 맞게 에이징 되는 금속 스털링 실버로 제작', '#목걸이', 800000, '2024-02-23', '2024-03-22', '2024-03-29', '2024-04-05', 'Y');


















